SEO-3147 JS Desc too long short
syncfusion-content/javascript-docs pull request #286
Opened 2023-01-27 12:11 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Please review the changes for JS Desc too long short.

Regards,
Yvone.

2023-01-27 12:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/console)**

2023-01-27 12:13 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/)<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/138/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-27 14:37 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/console)**

2023-01-27 14:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/console)**

2023-01-27 14:45 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/)<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/139/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-01 08:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/console)**

2023-02-01 08:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/147/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-07 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/console)**

2023-02-07 12:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/153/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-08 12:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/console)**

2023-02-08 12:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/156/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-09 12:09 UTC, Aishwarya-Ganesan commented on js/DateRangePicker/display-format.md
> +# Display Format in Essential JavaScript DateRangePicker
Remove Essential word.

2023-02-09 12:09 UTC, Aishwarya-Ganesan reviewed
Commented.

2023-02-09 12:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/console)**

2023-02-09 12:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/157/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 06:32 UTC, gowthamanthavasiyappan requested changes

2023-02-17 06:32 UTC, gowthamanthavasiyappan commented on js/DateTimePicker/Overview.md
> +# Overview in Essential JavaScript DateTimePicker
Remove Essential word.

2023-02-17 06:32 UTC, gowthamanthavasiyappan commented on js/Grid/Overview.md
> +# Overview in Essential JavaScript Grid
Remove Essential word.

2023-02-17 06:32 UTC, gowthamanthavasiyappan commented on js/ReportDesigner/Compose-Report/Configure-ReportItem/Line-ReportItem.md
> +# Line in Essential JavaScript ReportDesigner
Remove Essential word.

2023-02-17 06:32 UTC, gowthamanthavasiyappan commented
Commented

2023-02-17 06:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/console)**

2023-02-17 06:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3147-JS-Desc-too-long-short](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/178/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 06:51 UTC, Yvone-Atieno commented on js/ReportDesigner/Compose-Report/Configure-ReportItem/Line-ReportItem.md
> +# Line in Essential JavaScript ReportDesigner
removed

2023-02-17 06:51 UTC, Yvone-Atieno commented on js/Grid/Overview.md
> +# Overview in Essential JavaScript Grid
removed

2023-02-17 06:52 UTC, Yvone-Atieno commented on js/DateTimePicker/Overview.md
> +# Overview in Essential JavaScript DateTimePicker
removed

2023-02-17 07:10 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 05:43 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-02-21 05:43 UTC, merged