SEO-3267 - JS overview http to https
syncfusion-content/javascript-docs pull request #307
Opened 2023-02-16 09:05 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
please review the changes for JS overview.

Regards,
Sharly A.

2023-02-16 09:06 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/176/console)**

2023-02-16 12:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/console)**

2023-02-16 12:17 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/)<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/177/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-17 15:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/console)**

2023-02-17 15:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/179/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-21 04:08 UTC, gowthamanthavasiyappan requested changes

2023-02-21 04:08 UTC, gowthamanthavasiyappan commented on js/Overview.md
> +title: About Essential JavaScript Platform | Syncfusion
Revert this.

2023-02-21 04:08 UTC, gowthamanthavasiyappan commented
Commented

2023-02-21 04:44 UTC, Sharly-Atieno commented on js/Overview.md
> +title: About Essential JavaScript Platform | Syncfusion
done

2023-02-21 04:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/console)**

2023-02-21 04:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3267-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/187/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-02-21 04:53 UTC, gowthamanthavasiyappan approved these changes

2023-02-21 04:53 UTC, gowthamanthavasiyappan commented
Approved

2023-02-21 05:26 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-02-21 05:26 UTC, merged