SEO-3569 JavaScript Site Audit
syncfusion-content/javascript-docs pull request #327
Opened 2023-04-04 15:39 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Have changed title, description, H1 and named images.

Regards,
Yvone.

2023-04-04 15:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3569-JavaScript-Site-audit](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/206/console)**

2023-04-04 15:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3569-JavaScript-Site-audit](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/206/)<br/>**

2023-04-05 06:06 UTC, gowthamanthavasiyappan requested changes
Commented

2023-04-05 06:06 UTC, gowthamanthavasiyappan commented on js/PivotGrid/OLAP-Connectivity.md
> +description: Learn here more about oLAP connection types support in Syncfusion Essential JavaScript PivotGrid Control, its elements, and more.
Change like - OLAP connection types

2023-04-05 06:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3569-JavaScript-Site-audit](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/207/console)**

2023-04-05 06:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3569-JavaScript-Site-audit](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/207/)<br/>**

2023-04-05 08:24 UTC, Yvone-Atieno commented on js/PivotGrid/OLAP-Connectivity.md
> +description: Learn here more about oLAP connection types support in Syncfusion Essential JavaScript PivotGrid Control, its elements, and more.
changed

2023-04-05 08:46 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-04-13 12:36 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-04-13 12:37 UTC, merged