SEO-172101-Links-With-Redirects-JS-Overview
syncfusion-content/javascript-docs pull request #351
Opened 2023-05-26 07:56 UTC by berylouma

Hello,

I have worked on the links with redirects.

Regards,
Beryl.

2023-05-26 07:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172101-Links-With-Redirects-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/232/console)**

2023-05-26 07:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172101-Links-With-Redirects-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/232/)<br/>**

2023-06-05 13:48 UTC, MallikaRK requested changes
Commented

2023-06-05 13:48 UTC, MallikaRK commented on js/Overview.md
> +* Similar to the [Knowledge Base](https://support.syncfusion.com/kb/retiredproducts/category/94), the [forum](https://www.syncfusion.com/forums/javascript) section also contains responses to question
your updated URL seems wrong. Please use the below URL, 
https://support.syncfusion.com/kb/web/category/70

2023-06-12 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172101-Links-With-Redirects-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/243/console)**

2023-06-12 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172101-Links-With-Redirects-JS-Overview](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/243/)<br/>**

2023-06-12 08:59 UTC, MallikaRK approved these changes
Approved

2023-06-15 08:49 UTC, Girija-Rajendran approved these changes

2023-06-15 08:58 UTC, merged