SEO-174801 - JS-Multiple-H1
syncfusion-content/javascript-docs pull request #379
Opened 2023-08-02 13:01 UTC by amyprudencekingstone

Hi @MallikaRK ,
Worked , alt text correction, image name correction,d and description. Kindly review.

Regards,
Amy Kingstone.

2023-08-07 09:46 UTC, MallikaRK requested changes
Commented

2023-08-07 09:46 UTC, MallikaRK commented on js/AureliaJS.md
>  # Catalog application
why # H1 tag is added here?

2023-08-07 09:52 UTC, amyprudencekingstone commented on js/AureliaJS.md
>  # Catalog application
made changes

2023-08-07 09:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174801-JS-Multiple-H1](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/258/console)**

2023-08-08 10:13 UTC, MallikaRK approved these changes
Approved

2023-08-14 10:04 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-14 10:04 UTC, merged