SEO-177700-JS-dropped-keywords-issue-fixes
syncfusion-content/javascript-docs pull request #435
Opened 2023-12-06 14:15 UTC by Edithabich

Hi @gowthamanthavasiyappan ,
Please review the changes.
Thanks.
Regards,
Edith.

2023-12-06 14:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-177700-JS-dropped-keywords-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/318/console)**

2023-12-06 14:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-177700-JS-dropped-keywords-issue-fixes](https://jenkins.syncfusion.com/job/Content/job/javascript-docs/318/)<br/>**

2023-12-08 11:29 UTC, gowthamanthavasiyappan requested changes
Commented

2023-12-19 14:01 UTC, Edithabich commented on js/DateTimePicker/Getting-Started.md
> +title: Getting Started with JavaScript DateTime Picker | Syncfusion
resolved

2023-12-19 14:01 UTC, Edithabich commented on js/DateTimePicker/Getting-Started.md
> +description: Learn here about getting started with Syncfusion Essential JavaScript DateTime PIcker Control, its elements, and more details.
resolved

2024-01-04 11:47 UTC, gowthamanthavasiyappan approved these changes
Approved

2024-01-25 11:50 UTC, merged