SEO-174654-JavaScript-Image-With-anchor-text
syncfusion-content/javascript-docs pull request #504
Opened 2024-08-21 07:07 UTC by Omanyadick

Hi @Aishwarya-Ganesan, Kindly review my PR below.

2024-08-21 07:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/36/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-21 12:35 UTC, Yvone-Atieno requested changes
Commented

2024-08-22 08:50 UTC, Omanyadick commented on js/PdfViewer/Getting-Started.md
> +![Getting Started with PDF Viewer.](Getting-Started_images/getting-started-with-pdf-viewer.jpeg)
Resolved

2024-08-22 08:50 UTC, Omanyadick commented on js/PdfViewer/Getting-Started.md
> +![Getting Started with default HTML.](Getting-Started_images/getting-started-with-default-html.jpeg)
Checked

2024-08-22 13:00 UTC, Yvone-Atieno requested changes
Commented

2024-08-28 07:31 UTC, Omanyadick commented on js/PdfViewer/Getting-Started.md
> +![Creation Wizard in JavaScript PDF Viewer.](getting-started_images/creation-wizard-in-javascript-pdf-viewer.jpeg)
correct casing used.

2024-08-28 07:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/42/console)**

2024-08-28 09:31 UTC, Yvone-Atieno requested changes
Commented

2024-08-28 09:31 UTC, Yvone-Atieno commented on js/PdfViewer/Getting-Started.md
> +![Sample application in JavaScript PDF Viewer.](getting-started_images/sample-application-in-javascript-pdf-viewer.png)
Check image Alt

2024-08-28 09:49 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/)<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/46/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-28 09:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/47/console)**

2024-08-28 12:00 UTC, Yvone-Atieno approved these changes
Approved

2024-08-28 12:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/console)**

2024-08-28 12:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/48/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-05 05:28 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-05 05:28 UTC, merged