SEO-174654-JavaScript-Image-With-anchor-text-two
syncfusion-content/javascript-docs pull request #505
Opened 2024-08-21 07:18 UTC by Omanyadick

Hi @Aishwarya-Ganesan, Kindly review my Prs in the task below.

2024-08-21 07:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text-two](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/console)**

2024-08-21 07:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174654-JavaScript-Image-With-anchor-text-two](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/javascript-docs/37/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-22 13:08 UTC, Yvone-Atieno requested changes
Commented

2024-08-22 13:08 UTC, Yvone-Atieno commented on js/PdfViewer/Localization.md
> +![Localization in JavaScript PDF Viewer.](localization_images/localization-in-javascript-pdf-viewer.png)
Check image Alt

2024-08-28 07:49 UTC, Omanyadick commented on js/PdfViewer/Localization.md
> +![Localization in JavaScript PDF Viewer.](localization_images/localization-in-javascript-pdf-viewer.png)
Alt text resolved

2024-08-28 09:22 UTC, Yvone-Atieno approved these changes
Approved

2024-09-05 05:29 UTC, Aishwarya-Ganesan approved these changes
fine.

2024-09-05 05:29 UTC, merged